<?php
/**
 * Magento
 * @category   Payment
 * @package    Pdt_ir123pay
 * @copyright  Copyright (c) 2013 123pay Development Team
 * @see http://123pay.ir
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>"
      lang="<?php echo $this->getLang() ?>">
<head>
</head>
<body>
<?php echo $this->getChildHtml( 'content' ) ?>
</body>
</html>
