<?php
/**
 * Magento
 * @category   Payment
 * @package    Pdt_ir123pay
 * @copyright  Copyright (c) 2013 123pay Development Team
 * @see http://123pay.ir
 */
?>
<fieldset class="form-list">
	<?php $_code = $this->getMethodCode() ?>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            به درگاه یک دو سه پی ارجاع داده خواهید شد
        </li>
    </ul>
</fieldset>