<?php
/**
 * Magento
 * @category   Payment
 * @package    Pdt__123pay
 * @copyright  Copyright (c) 2013 123pay Development Team
 * @see http://123pay.ir
 */
?>
<html>
<meta http-equiv="refresh" content="0; URL=<?php echo $this->getContinueShoppingUrl() ?>">
<body>
<div class="page-head">
    <h3><?php echo $this->__( 'خطایی رخ داد' ) ?></h3>
</div>
<p><?php echo $this->__( 'با عرض پوزش خطایی در روند خرید رخ داد <a href="%s">ادامه خرید</a>.', $this->getContinueShoppingUrl() ) ?></p>
</body>
</html>